
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/weeklyjpa
    username: root
    password: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true